server:
  port: 8082
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping? characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
ribbitmq:
  host: 123.56.249.187
  port: 5672
  username: guest
  password: guest
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
redis:
  maxTotal: 8
  maxIdle: 8
  minIdle: 0
  blockWhenExhausted: true
  maxWaitMillis: 10000
  testOnBorrow: true
  testOnReturn: true
  jmxEnabled: true
  redisHost: 123.56.249.187
  redisPort: 6379
  redisPassword: 123456
  timeout: 1000
